// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: storageServer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreHumidityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId  int32 `protobuf:"varint,1,opt,name=plantId,proto3" json:"plantId,omitempty"`
	Humidity int32 `protobuf:"varint,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
}

func (x *StoreHumidityRequest) Reset() {
	*x = StoreHumidityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreHumidityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHumidityRequest) ProtoMessage() {}

func (x *StoreHumidityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHumidityRequest.ProtoReflect.Descriptor instead.
func (*StoreHumidityRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{0}
}

func (x *StoreHumidityRequest) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *StoreHumidityRequest) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

type GetThumbnailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetThumbnailsRequest) Reset() {
	*x = GetThumbnailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetThumbnailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailsRequest) ProtoMessage() {}

func (x *GetThumbnailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailsRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailsRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{1}
}

type GetAllPlantsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllPlantsRequest) Reset() {
	*x = GetAllPlantsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPlantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPlantsRequest) ProtoMessage() {}

func (x *GetAllPlantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPlantsRequest.ProtoReflect.Descriptor instead.
func (*GetAllPlantsRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{2}
}

type PlantThumbnailReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Images []*PlantThumbnailMsg `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *PlantThumbnailReply) Reset() {
	*x = PlantThumbnailReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantThumbnailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantThumbnailReply) ProtoMessage() {}

func (x *PlantThumbnailReply) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantThumbnailReply.ProtoReflect.Descriptor instead.
func (*PlantThumbnailReply) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{3}
}

func (x *PlantThumbnailReply) GetImages() []*PlantThumbnailMsg {
	if x != nil {
		return x.Images
	}
	return nil
}

type PlantThumbnailMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId int32  `protobuf:"varint,1,opt,name=plantId,proto3" json:"plantId,omitempty"`
	Image   []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *PlantThumbnailMsg) Reset() {
	*x = PlantThumbnailMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantThumbnailMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantThumbnailMsg) ProtoMessage() {}

func (x *PlantThumbnailMsg) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantThumbnailMsg.ProtoReflect.Descriptor instead.
func (*PlantThumbnailMsg) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{4}
}

func (x *PlantThumbnailMsg) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *PlantThumbnailMsg) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plant int32 `protobuf:"varint,1,opt,name=plant,proto3" json:"plant,omitempty"`
}

func (x *GetPlantRequest) Reset() {
	*x = GetPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantRequest) ProtoMessage() {}

func (x *GetPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantRequest.ProtoReflect.Descriptor instead.
func (*GetPlantRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlantRequest) GetPlant() int32 {
	if x != nil {
		return x.Plant
	}
	return 0
}

type DeletePlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plant int32 `protobuf:"varint,1,opt,name=plant,proto3" json:"plant,omitempty"`
}

func (x *DeletePlantRequest) Reset() {
	*x = DeletePlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantRequest) ProtoMessage() {}

func (x *DeletePlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantRequest.ProtoReflect.Descriptor instead.
func (*DeletePlantRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePlantRequest) GetPlant() int32 {
	if x != nil {
		return x.Plant
	}
	return 0
}

type DeletePlantReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePlantReply) Reset() {
	*x = DeletePlantReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePlantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePlantReply) ProtoMessage() {}

func (x *DeletePlantReply) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePlantReply.ProtoReflect.Descriptor instead.
func (*DeletePlantReply) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{7}
}

type StoreHumidityReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreHumidityReply) Reset() {
	*x = StoreHumidityReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreHumidityReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreHumidityReply) ProtoMessage() {}

func (x *StoreHumidityReply) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreHumidityReply.ProtoReflect.Descriptor instead.
func (*StoreHumidityReply) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{8}
}

type AllPlantsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plants []*PlantOverviewMsg `protobuf:"bytes,1,rep,name=plants,proto3" json:"plants,omitempty"`
}

func (x *AllPlantsReply) Reset() {
	*x = AllPlantsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllPlantsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllPlantsReply) ProtoMessage() {}

func (x *AllPlantsReply) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllPlantsReply.ProtoReflect.Descriptor instead.
func (*AllPlantsReply) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{9}
}

func (x *AllPlantsReply) GetPlants() []*PlantOverviewMsg {
	if x != nil {
		return x.Plants
	}
	return nil
}

type AddPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId        int32    `protobuf:"varint,1,opt,name=plantId,proto3" json:"plantId,omitempty"`
	Name           string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Info           string   `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	GpioSensorSlot int32    `protobuf:"varint,4,opt,name=gpioSensorSlot,proto3" json:"gpioSensorSlot,omitempty"`
	Images         [][]byte `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *AddPlantRequest) Reset() {
	*x = AddPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPlantRequest) ProtoMessage() {}

func (x *AddPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPlantRequest.ProtoReflect.Descriptor instead.
func (*AddPlantRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{10}
}

func (x *AddPlantRequest) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *AddPlantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddPlantRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *AddPlantRequest) GetGpioSensorSlot() int32 {
	if x != nil {
		return x.GpioSensorSlot
	}
	return 0
}

func (x *AddPlantRequest) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

type PlantOverviewMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId        int32  `protobuf:"varint,1,opt,name=plantId,proto3" json:"plantId,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Info           string `protobuf:"bytes,3,opt,name=Info,proto3" json:"Info,omitempty"`
	GpioSensorSlot int32  `protobuf:"varint,4,opt,name=gpioSensorSlot,proto3" json:"gpioSensorSlot,omitempty"`
	Thumbnail      []byte `protobuf:"bytes,5,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
}

func (x *PlantOverviewMsg) Reset() {
	*x = PlantOverviewMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlantOverviewMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlantOverviewMsg) ProtoMessage() {}

func (x *PlantOverviewMsg) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlantOverviewMsg.ProtoReflect.Descriptor instead.
func (*PlantOverviewMsg) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{11}
}

func (x *PlantOverviewMsg) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

func (x *PlantOverviewMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlantOverviewMsg) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *PlantOverviewMsg) GetGpioSensorSlot() int32 {
	if x != nil {
		return x.GpioSensorSlot
	}
	return 0
}

func (x *PlantOverviewMsg) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

type GetAdditionalDataPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlantId int32 `protobuf:"varint,1,opt,name=plantId,proto3" json:"plantId,omitempty"`
}

func (x *GetAdditionalDataPlantRequest) Reset() {
	*x = GetAdditionalDataPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdditionalDataPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdditionalDataPlantRequest) ProtoMessage() {}

func (x *GetAdditionalDataPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdditionalDataPlantRequest.ProtoReflect.Descriptor instead.
func (*GetAdditionalDataPlantRequest) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{12}
}

func (x *GetAdditionalDataPlantRequest) GetPlantId() int32 {
	if x != nil {
		return x.PlantId
	}
	return 0
}

type HumidityMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Humidity  int32                  `protobuf:"varint,1,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HumidityMsg) Reset() {
	*x = HumidityMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumidityMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumidityMsg) ProtoMessage() {}

func (x *HumidityMsg) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumidityMsg.ProtoReflect.Descriptor instead.
func (*HumidityMsg) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{13}
}

func (x *HumidityMsg) GetHumidity() int32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *HumidityMsg) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetAdditionalDataPlantReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plant      int32                  `protobuf:"varint,1,opt,name=plant,proto3" json:"plant,omitempty"`
	SensorSlot int32                  `protobuf:"varint,2,opt,name=SensorSlot,proto3" json:"SensorSlot,omitempty"`
	Watered    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=Watered,proto3" json:"Watered,omitempty"`
	Humidity   []*HumidityMsg         `protobuf:"bytes,4,rep,name=Humidity,proto3" json:"Humidity,omitempty"`
	Images     [][]byte               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
}

func (x *GetAdditionalDataPlantReply) Reset() {
	*x = GetAdditionalDataPlantReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_storageServer_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdditionalDataPlantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdditionalDataPlantReply) ProtoMessage() {}

func (x *GetAdditionalDataPlantReply) ProtoReflect() protoreflect.Message {
	mi := &file_storageServer_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdditionalDataPlantReply.ProtoReflect.Descriptor instead.
func (*GetAdditionalDataPlantReply) Descriptor() ([]byte, []int) {
	return file_storageServer_proto_rawDescGZIP(), []int{14}
}

func (x *GetAdditionalDataPlantReply) GetPlant() int32 {
	if x != nil {
		return x.Plant
	}
	return 0
}

func (x *GetAdditionalDataPlantReply) GetSensorSlot() int32 {
	if x != nil {
		return x.SensorSlot
	}
	return 0
}

func (x *GetAdditionalDataPlantReply) GetWatered() *timestamppb.Timestamp {
	if x != nil {
		return x.Watered
	}
	return nil
}

func (x *GetAdditionalDataPlantReply) GetHumidity() []*HumidityMsg {
	if x != nil {
		return x.Humidity
	}
	return nil
}

func (x *GetAdditionalDataPlantReply) GetImages() [][]byte {
	if x != nil {
		return x.Images
	}
	return nil
}

var File_storageServer_proto protoreflect.FileDescriptor

var file_storageServer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d,
	0x65, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x48, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x4c, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x35, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68,
	0x6f, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22, 0x43, 0x0a,
	0x11, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x4d,
	0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x0a, 0x12, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x46, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x34, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65,
	0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x4d, 0x73,
	0x67, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x22, 0x93, 0x01, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x26, 0x0a, 0x0e, 0x67, 0x70, 0x69, 0x6f, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x6c, 0x6f,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x67, 0x70, 0x69, 0x6f, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x9a, 0x01, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x4f, 0x76, 0x65, 0x72, 0x76, 0x69, 0x65,
	0x77, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x67, 0x70, 0x69, 0x6f, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e,
	0x67, 0x70, 0x69, 0x6f, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x6c, 0x6f, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x22, 0x39, 0x0a, 0x1d,
	0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x63, 0x0a, 0x0b, 0x48, 0x75, 0x6d, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x75, 0x6d, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0xd6, 0x01, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x6c, 0x61,
	0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x6c, 0x6f, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x53, 0x6c,
	0x6f, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x57, 0x61, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x07, 0x57, 0x61, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x48, 0x75, 0x6d, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79,
	0x4d, 0x73, 0x67, 0x52, 0x08, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x73, 0x32, 0xa6, 0x04, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x4f, 0x76,
	0x65, 0x72, 0x76, 0x69, 0x65, 0x77, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x12,
	0x1f, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x6c,
	0x6c, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x6e,
	0x0a, 0x16, 0x67, 0x65, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x29, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74,
	0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x4a,
	0x0a, 0x0b, 0x61, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x1b, 0x2e,
	0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x50, 0x6c,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x4f, 0x76, 0x65,
	0x72, 0x76, 0x69, 0x65, 0x77, 0x4d, 0x73, 0x67, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0b, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x1e, 0x2e, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x6d, 0x61, 0x72,
	0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x12, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x20, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x48, 0x75, 0x6d, 0x69, 0x64, 0x69,
	0x74, 0x79, 0x46, 0x6f, 0x72, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x20, 0x2e, 0x73, 0x6d, 0x61,
	0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x48, 0x75, 0x6d,
	0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73,
	0x6d, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x48,
	0x75, 0x6d, 0x69, 0x64, 0x69, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x5a,
	0x0a, 0x1e, 0x63, 0x6f, 0x6d, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x72, 0x70,
	0x69, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x76, 0x31,
	0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x62,
	0x69, 0x61, 0x73, 0x6a, 0x75, 0x6e, 0x67, 0x6d, 0x61, 0x6e, 0x6e, 0x2f, 0x48, 0x69, 0x6d, 0x62,
	0x65, 0x65, 0x72, 0x67, 0x61, 0x72, 0x74, 0x65, 0x6e, 0x5f, 0x52, 0x50, 0x69, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_storageServer_proto_rawDescOnce sync.Once
	file_storageServer_proto_rawDescData = file_storageServer_proto_rawDesc
)

func file_storageServer_proto_rawDescGZIP() []byte {
	file_storageServer_proto_rawDescOnce.Do(func() {
		file_storageServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_storageServer_proto_rawDescData)
	})
	return file_storageServer_proto_rawDescData
}

var file_storageServer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_storageServer_proto_goTypes = []interface{}{
	(*StoreHumidityRequest)(nil),          // 0: smart_home.StoreHumidityRequest
	(*GetThumbnailsRequest)(nil),          // 1: smart_home.GetThumbnailsRequest
	(*GetAllPlantsRequest)(nil),           // 2: smart_home.GetAllPlantsRequest
	(*PlantThumbnailReply)(nil),           // 3: smart_home.PlantThumbnailReply
	(*PlantThumbnailMsg)(nil),             // 4: smart_home.PlantThumbnailMsg
	(*GetPlantRequest)(nil),               // 5: smart_home.GetPlantRequest
	(*DeletePlantRequest)(nil),            // 6: smart_home.DeletePlantRequest
	(*DeletePlantReply)(nil),              // 7: smart_home.DeletePlantReply
	(*StoreHumidityReply)(nil),            // 8: smart_home.StoreHumidityReply
	(*AllPlantsReply)(nil),                // 9: smart_home.AllPlantsReply
	(*AddPlantRequest)(nil),               // 10: smart_home.AddPlantRequest
	(*PlantOverviewMsg)(nil),              // 11: smart_home.PlantOverviewMsg
	(*GetAdditionalDataPlantRequest)(nil), // 12: smart_home.GetAdditionalDataPlantRequest
	(*HumidityMsg)(nil),                   // 13: smart_home.HumidityMsg
	(*GetAdditionalDataPlantReply)(nil),   // 14: smart_home.GetAdditionalDataPlantReply
	(*timestamppb.Timestamp)(nil),         // 15: google.protobuf.Timestamp
}
var file_storageServer_proto_depIdxs = []int32{
	4,  // 0: smart_home.PlantThumbnailReply.images:type_name -> smart_home.PlantThumbnailMsg
	11, // 1: smart_home.AllPlantsReply.plants:type_name -> smart_home.PlantOverviewMsg
	15, // 2: smart_home.HumidityMsg.timestamp:type_name -> google.protobuf.Timestamp
	15, // 3: smart_home.GetAdditionalDataPlantReply.Watered:type_name -> google.protobuf.Timestamp
	13, // 4: smart_home.GetAdditionalDataPlantReply.Humidity:type_name -> smart_home.HumidityMsg
	2,  // 5: smart_home.StorageServer.getOverviewAllPlants:input_type -> smart_home.GetAllPlantsRequest
	12, // 6: smart_home.StorageServer.getAdditionalDataPlant:input_type -> smart_home.GetAdditionalDataPlantRequest
	10, // 7: smart_home.StorageServer.addNewPlant:input_type -> smart_home.AddPlantRequest
	6,  // 8: smart_home.StorageServer.deletePlant:input_type -> smart_home.DeletePlantRequest
	0,  // 9: smart_home.StorageServer.storeHumidityEntry:input_type -> smart_home.StoreHumidityRequest
	0,  // 10: smart_home.StorageServer.getHumidityForPlant:input_type -> smart_home.StoreHumidityRequest
	9,  // 11: smart_home.StorageServer.getOverviewAllPlants:output_type -> smart_home.AllPlantsReply
	14, // 12: smart_home.StorageServer.getAdditionalDataPlant:output_type -> smart_home.GetAdditionalDataPlantReply
	11, // 13: smart_home.StorageServer.addNewPlant:output_type -> smart_home.PlantOverviewMsg
	7,  // 14: smart_home.StorageServer.deletePlant:output_type -> smart_home.DeletePlantReply
	8,  // 15: smart_home.StorageServer.storeHumidityEntry:output_type -> smart_home.StoreHumidityReply
	8,  // 16: smart_home.StorageServer.getHumidityForPlant:output_type -> smart_home.StoreHumidityReply
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_storageServer_proto_init() }
func file_storageServer_proto_init() {
	if File_storageServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_storageServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreHumidityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetThumbnailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPlantsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantThumbnailReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantThumbnailMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePlantReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreHumidityReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllPlantsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlantOverviewMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdditionalDataPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumidityMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_storageServer_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdditionalDataPlantReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_storageServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storageServer_proto_goTypes,
		DependencyIndexes: file_storageServer_proto_depIdxs,
		MessageInfos:      file_storageServer_proto_msgTypes,
	}.Build()
	File_storageServer_proto = out.File
	file_storageServer_proto_rawDesc = nil
	file_storageServer_proto_goTypes = nil
	file_storageServer_proto_depIdxs = nil
}
