// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: storageServer.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StorageServerClient is the client API for StorageServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServerClient interface {
	StoreHumidityEntry(ctx context.Context, in *StoreHumidityRequest, opts ...grpc.CallOption) (*StoreHumidityReply, error)
}

type storageServerClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServerClient(cc grpc.ClientConnInterface) StorageServerClient {
	return &storageServerClient{cc}
}

func (c *storageServerClient) StoreHumidityEntry(ctx context.Context, in *StoreHumidityRequest, opts ...grpc.CallOption) (*StoreHumidityReply, error) {
	out := new(StoreHumidityReply)
	err := c.cc.Invoke(ctx, "/smart_home.StorageServer/storeHumidityEntry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServerServer is the server API for StorageServer service.
// All implementations must embed UnimplementedStorageServerServer
// for forward compatibility
type StorageServerServer interface {
	StoreHumidityEntry(context.Context, *StoreHumidityRequest) (*StoreHumidityReply, error)
	mustEmbedUnimplementedStorageServerServer()
}

// UnimplementedStorageServerServer must be embedded to have forward compatible implementations.
type UnimplementedStorageServerServer struct {
}

func (UnimplementedStorageServerServer) StoreHumidityEntry(context.Context, *StoreHumidityRequest) (*StoreHumidityReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreHumidityEntry not implemented")
}
func (UnimplementedStorageServerServer) mustEmbedUnimplementedStorageServerServer() {}

// UnsafeStorageServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServerServer will
// result in compilation errors.
type UnsafeStorageServerServer interface {
	mustEmbedUnimplementedStorageServerServer()
}

func RegisterStorageServerServer(s grpc.ServiceRegistrar, srv StorageServerServer) {
	s.RegisterService(&StorageServer_ServiceDesc, srv)
}

func _StorageServer_StoreHumidityEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreHumidityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServerServer).StoreHumidityEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smart_home.StorageServer/storeHumidityEntry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServerServer).StoreHumidityEntry(ctx, req.(*StoreHumidityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageServer_ServiceDesc is the grpc.ServiceDesc for StorageServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smart_home.StorageServer",
	HandlerType: (*StorageServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "storeHumidityEntry",
			Handler:    _StorageServer_StoreHumidityEntry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storageServer.proto",
}
